version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync build s3://freejson.john-shenk.com
      - aws s3 sync build s3://freejson.json.ninja
      - aws cloudfront create-invalidation --paths /index.html --distribution-id E11BTYW60UMYFH
      - aws cloudfront create-invalidation --paths /index.html --distribution-id E2098WBK5XLN5A
artifacts:
  files:
    - 'build/*'

